#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (C) 2022 Ing
#


name: Build OpenWrt-GL-MT3000

on:
  schedule:
    - cron: '0 16 1,15 * *'
    #每个月的1号和15号的UTC时间16点即中国时间夜里12点编译一次
  repository_dispatch:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/hanwckf/immortalwrt-mt798x.git
  REPO_BRANCH: openwrt-21.02
  #FEEDS_CONF: h68k.feeds.conf.default
  CONFIG_FILE: mt-3000.config
  DIY_SHELL: mt3kdiy.sh
  TZ: Asia/Shanghai


jobs:
  build:
    name: Build OpenWrt-GL-MT3000
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Init Env
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: init build
      run: |
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SHELL
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SHELL

    - name: Make menuconfig
      run: |
           cd openwrt
           make defconfig

    - name: Check and Push config
      run: |
        [ -e $CONFIG_FILE ] && cp openwrt/.config $CONFIG_FILE
        if [ -n "$(git status -s | grep $CONFIG_FILE)" ]; then
          git add $CONFIG_FILE
          git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
          git push -f
        fi

    - name: Compile the firmware
      run: |
        cd openwrt
        echo -e "download package"
        make download -j8

        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s

        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > device_name
        [ -s device_name ] && echo "device_name=_$(cat device_name)" >> $GITHUB_ENV
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    - name: Organize files
      if: (!cancelled())
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages *.buildinfo *.manifest *.bin
        sed -i '/buildinfo/d; /\.bin/d; /\.manifest/d' sha256sums
        for i in `ls` ; do gzip $i; done
        echo "firmware_dir=$PWD" >> $GITHUB_ENV

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: (!cancelled())
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release_tag }}
        files: ${{ env.firmware_dir }}/*

    #- name: Delete workflow runs
    #  uses: Mattraks/delete-workflow-runs@v2
    #  with:
    #    retain_days: 1
    #    keep_minimum_runs: 9

   # - name: Remove old Releases
   #   uses: dev-drprasad/delete-older-releases@v0.2.0
   #   with:
   #     keep_latest: 9
   #     delete_tags: true
   #   env:
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
