#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (C) 2022 Ing
#


name: Build immortalwrt-H68K

on:
  workflow_dispatch:


env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-24.10
  CONFIG_FILE: h68k/immortalwrt.config
  DIY_SHELL: h68k/immortalwrt-diy.sh
  TZ: Asia/Shanghai
  DEVICE: hinlink_h68k
  SOURCE_REPO: immortalwrt


jobs:
  build:
    name: Build OpenWrt-H68K
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Init Env
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "$TZ"
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E apt-get autoremove --purge
        sudo -E apt-get clean
    
    - name: Clone source code
      run: |
        df -hT
        pwd
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        cp ../patch/add-support.sh .
        bash add-support.sh
        cp ../patch/001-add-h68k-support.patch package/boot/uboot-rockchip/patches/
    
    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Clone luci-app-argon
      run: |
           cd openwrt
           rm -rf package/feeds/luci/luci-app-argon-config
           rm -rf package/feeds/luci/luci-theme-argon
           git clone https://github.com/jerrykuku/luci-theme-argon.git package/feeds/luci/luci-theme-argon
           git clone https://github.com/jerrykuku/luci-app-argon-config.git package/feeds/luci-app-argon-config
           
    - name: Load custom configuration
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        chmod +x $DIY_SHELL
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SHELL
    
    - name: Make menuconfig
      run: |
           cd openwrt
           make defconfig
    
    - name: Check and Push config
      run: |
        [ -e $CONFIG_FILE ] && cp openwrt/.config $CONFIG_FILE
        if [ -n "$(git status -s | grep $CONFIG_FILE)" ]; then
          git add $CONFIG_FILE
          git commit -m "update config"
          git push -f
        fi
  
    - name: Compile the firmware
      run: |
        cd openwrt
        echo -e "download package"
        make download -j$(nproc)
        echo -e "$(nproc) thread compile"
        make -j$(nproc) V=s
        echo "release=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
    
    - name: Check space usage
      if: (!cancelled())
      run: |
        df -hT

    - name: Organize files
      if: (!cancelled())
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages *.buildinfo *.manifest *.bin
        sed -i '/buildinfo/d; /\.bin/d; /\.manifest/d' sha256sums
        for i in `ls` ; do gzip $i; done
        echo "firmware_dir=$PWD" >> $GITHUB_ENV
    
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v2
      if: (!cancelled())
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.release }}-${{ env.DEVICES }}-${{ env.SOURCE_REPO }}
        release_name: "OpenWrt Firmware - ${{ env.release }}-${{ env.DEVICE }}"
        body: |
          **OpenWrt Image Information**

          - **Default IP:** 192.168.100.1
          - **Default WAN:** eth2
          - **Default Username:** root
          - **Default Password:** none
          - **Default WIFI Name:** immrotalwrt
          - **Default WIFI Password:** none

          **OpenWrt Source Code**
          - ${{ env.REPO_URL }}
        files: ${{ env.firmware_dir }}/*

